version: 0.0.{build}
skip_tags: true
build:
  project: timeSignal.sln
  verbosity: minimal
image: Visual Studio 2015
configuration: Debug
before_build:
  - nuget restore timeSignal.sln
  - git clone -q --branch=master https://github.com/mamori017/Common.git ..\Common
